feat: login page
BaanJo-Chula/group-annoucement pull request #7
Opened 2023-07-30 15:55 UTC by paxzes

2023-07-30 17:16 UTC, shalluv requested changes
Furthermore, there are many unnecessary nested divs. Please double-check where simplification is possible.

At this point, you should insert the logo to replace the gray circle div.

2023-07-30 17:16 UTC, shalluv commented on src/pages/index.tsx
> +            <div className="h-1/3 w-full rounded-xl bg-gray-400"></div>
I assume that this is an input, right? Please use the `<input />` tag.

2023-07-30 17:16 UTC, shalluv commented on src/pages/index.tsx
> +    <div className="flex h-screen w-screen flex-col">
This is okay, but I prefer using `min-h-screen` and `w-full` instead of these.

2023-07-30 17:16 UTC, shalluv commented on src/pages/index.tsx
> +      <div className="bg-red-500 flex h-32 items-center justify-center">
There is no need to import Footer here, as Tar has already included it in the `_app.tsx` files.

2023-07-30 17:16 UTC, shalluv commented on src/pages/index.tsx
> +      <div className="bg-red-500 flex h-32 items-center justify-center">
Just add `pb-32` to the top-most div and it will be fine.

2023-07-30 17:16 UTC, shalluv commented on src/pages/index.tsx
> +          <div className="right-10px absolute -top-14 h-28 w-28 rounded-full bg-black sm:-top-16 sm:h-32 sm:w-32"></div>
The class name "right-10px" has no effect. If you intended to use an arbitrary value, you may want to use "right-[10px]" instead. 

However, I suggest using Tailwind classes that are as close to 10 as possible, but not necessarily exactly 10, for better results.

Anyway, there is no need to adjust this `div` to the right.

2023-07-30 17:16 UTC, shalluv commented on src/pages/index.tsx
> +        <div className="bg-red-700 border-red-200 relative flex h-1/3 w-4/6 max-w-lg flex-col items-center justify-center rounded-3xl border-4 border-solid">
I just added red to the Tailwind configuration, so now you should use `bg-red` and `border-red/20` to accurately match the design.

Anyway, this is not your fault. As I said, I just added them.

2023-07-31 01:18 UTC, paxzes commented
Please help me on background and logo. Also, border-red/20 doesn't work somehow. I'm dying laew.

2023-08-01 10:15 UTC, merged